name: jbdev
description: >
  A lightweight Flutter utility package containing custom extensions, validators, 
  and helper functions built for internal use across JBDEV apps and projects.
version: 0.0.2
homepage: https://jbdev.in
repository: https://github.com/jatinsakshiB/jbdev
issue_tracker: https://github.com/jatinsakshiB/jbdev/issues

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
