name: jbdev
description: >
  A lightweight Flutter utility package containing custom extensions, validators, 
  and helper functions built for internal use across JBDev apps and projects.
version: 0.0.1
homepage: https://jbdev.in
repository: https://github.com/jatinsakshiB/jbdev
issue_tracker: https://github.com/jatinsakshiB/jbdev/issues

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
